### ISSUE TITLE
Passwort Protected Links in README.md

### ISSUE THREAD

**Issue by holgerimbery** [microsoft/dynamics-365-contact-center#45]
Please update the links in README.md to non-password-protected links or share a way to access the linked documents, at least for partners.

**Comment by vertikapandey** [comment]
Hi @holgerimbery , thanks for raising this. I have raised a PR to get this removed from the README.

**Comment by vertikapandey** [comment]
The link is removed from README. Hence closing this issue.

**Comment by holgerimbery** [comment]
@vertikapandey:
you closed the issue, 
but "Set up D365 Contact Center embedded experience" --> https://review.learn.microsoft.com/en-us/dynamics365/contact-center/administer/set-up-embedded-experience?branch=main is still a non-public link, as it is pointing to the review site instead of the documentation. 

It should be https://learn.microsoft.com/en-us/dynamics365/contact-center/administer/set-up-embedded-experience
